### PR TITLE
Updated example file description and fixed one issue

### PR DESCRIPTION
**Pull request by Serhiy-Shekhovtsov**
Now the description says what exact files are required to run the example code. Took some time for me to find out what to put there :) . Also there was an issue with LDA Accuracy calculation, error was saying "'bool' object has no attribute 'sum'".
You can use http://nbviewer.ipython.org/ to compare .ipynb files online.

### CODE REVIEW

**Comment by venthur** [comment]
Here you go: https://gist.github.com/1b105d750053c6113eca.git

**Comment by Serhiy-Shekhovtsov** [comment]
What is this https://gist.github.com/1b105d750053c6113eca.git ? It shows an empty page.

**Comment by venthur** [comment]
Should be the true labels. Try this one instead: https://gist.github.com/venthur/1b105d750053c6113eca

**Comment by Serhiy-Shekhovtsov** [comment]
This one works, many thanks!

**Pull request closed without merging**
